name: snakemake
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake=8
  - graphviz=2.50.0
  - python=3.12
  - snakemake-executor-plugin-slurm
  - snakemake-storage-plugin-s3
  - mamba
  - pip
