run:
  liftover: False

# paths
workspace_path: 'results'
input_file: 'config/example.tsv'
uri: 'file:///~/tiledb'
#mongo_uri: 'mongodb://localhost:27017/tiledb'
vault_auth: "basic"
vault_mount_point: null
vault_path: null
vault_token: null
vault_url: null

chain_file: '/group/diangelantonio/public_data/liftOver/hg19ToHg38.over.chain.gz'
log: 'logfile_liftover'
hg37_fasta_fai_file: '/group/diangelantonio/public_data/liftOver/human_g1k_v37.fasta.fai'
hg38_fasta_file: '/group/diangelantonio/public_data/liftOver/hg38.fa'
hg38_fasta_fai_file: '/group/diangelantonio/public_data/liftOver/hg38.fa.fai'

params:
  harmonize_sumstats:
    input_format: "vcf"
    config_file: "config/config_harmonize_sumstats.yml"
