run:
  liftover: True

# paths
workspace_path: 'results'
sumstats_path: 'config/local.txt'
uri: '~/tiledb'
metadata_file: 'data/metadata.json'
chain_file: '/group/diangelantonio/public_data/liftOver/hg19ToHg38.over.chain.gz'
log: 'logfile_liftover'
hg37_fasta_fai_file: '/group/diangelantonio/public_data/liftOver/human_g1k_v37.fasta.fai'
hg38_fasta_file: '/group/diangelantonio/public_data/liftOver/hg38.fa'
hg38_fasta_fai_file: '/group/diangelantonio/public_data/liftOver/hg38.fa.fai'

params:
  harmonize_sumstats:
    input_format: "vcf"
    config_file: "config/config_harmonize_sumstats.yml"
