---
# common parameters
n_cores: &cores 4

# This is an ordered dict that contains the order in which the steps are run.
run_sequence: !!omap
  - 1: 'basic_check'
  - 2: 'infer_build'
  - 3: 'fill_data'
  - 4: 'harmonize'
  - 5: 'liftover'
  - 6: 'sort_alphabetically'
  - 7: 'write_tsv'


steps:
  basic_check: # see https://cloufield.github.io/gwaslab/Standardization/
    params:
      run: True
    gl_params:
      n_cores: *cores
      normalize: True
      fixid_args:
        fixid: True
        forcefixid: True
  infer_build: # see https://cloufield.github.io/gwaslab/InferBuild/
    params:
      run: True
  fill_data: # see https://cloufield.github.io/gwaslab/Conversion/#fill_data
    params:
      run: True
    gl_params:
      to_fill: ['MLOG10P', 'Z']
      overwrite: False
      extreme: True
  harmonize: # see https://cloufield.github.io/gwaslab/Harmonization/
    params:
      run: True
    gl_params:
      basic_check: False
      n_cores: *cores
  sort_alphabetically:
    params: # see https://cloufield.github.io/gwaslab/Harmonization/
      run: True
    gl_params:
      n_cores: *cores
  liftover: # see https://cloufield.github.io/gwaslab/LiftOver/
    params:
      run: True
    gl_params:
      n_cores: *cores
      from_build: "19"
      to_build: "38"
      remove: True

    
  write_tsv:
    params:
      run: True
      workspace: "outputs"
      workspace_subfolder: True
    gl_params:
      fmt: "gwaslab"
      to_csvargs:
        compression:
          method: "gzip"
          compresslevel: 1
          mtime: 1
      float_formats:
        BETA: '{:.5f}'
        SE: '{:.5f}'
        MLOG10P: '{:.5f}'
        EAF: '{:.5f}'

# Filename transformation, e.g.: ukb-a-1.vcf.gz
filename_mask: [ True, False, False]
filename_sep: '.'

# IO
root_path: "results"
log_filename: "gwaspipe.log"
formatbook_path: "workflow/scripts/gwaspipe/data/formatbook.json"     # fill this var if you want to provide a custom formatbook
